# -*- coding: utf-8 -*-
"""
Les villes du plan, telles qu'il les a fixees le 11 septembre :

    top 100 USA & CANADA · top 50 Europe · top 50 Moyen-Orient · top 50 Asie

Soit 250 villes, 250 pages. C'est SA decision apres avoir vu le calcul des
190 500 : il a garde la structure « une page par ville » et fixe le nombre.

« top 100 USA&CANADA » est compris comme 100 villes pour les DEUX pays
reunis, puisqu'il donne ensuite 50 par region. Si c'etait 100 chacun, c'est
une ligne a changer ici et rien d'autre.

Les villes sont REELLES : ce sont des lieux, pas des affirmations sur un
marche. Ce que la page dira de chacune, en revanche, reste a fournir — voir
l'encadre « ce qui manque » sur chaque page.

Format : (slug, nom, division, pays, langues)
"""

AMERIQUE_NORD = [
    ("new-york", "New York", "New York", "US", ["en"]),
    ("los-angeles", "Los Angeles", "California", "US", ["en", "es"]),
    ("toronto", "Toronto", "Ontario", "CA", ["en"]),
    ("chicago", "Chicago", "Illinois", "US", ["en"]),
    ("houston", "Houston", "Texas", "US", ["en", "es"]),
    ("montreal", "Montreal", "Quebec", "CA", ["fr", "en"]),
    ("phoenix", "Phoenix", "Arizona", "US", ["en", "es"]),
    ("philadelphia", "Philadelphia", "Pennsylvania", "US", ["en"]),
    ("san-antonio", "San Antonio", "Texas", "US", ["en", "es"]),
    ("san-diego", "San Diego", "California", "US", ["en", "es"]),
    ("dallas", "Dallas", "Texas", "US", ["en", "es"]),
    ("vancouver", "Vancouver", "British Columbia", "CA", ["en"]),
    ("austin", "Austin", "Texas", "US", ["en"]),
    ("calgary", "Calgary", "Alberta", "CA", ["en"]),
    ("jacksonville", "Jacksonville", "Florida", "US", ["en"]),
    ("san-jose", "San Jose", "California", "US", ["en"]),
    ("fort-worth", "Fort Worth", "Texas", "US", ["en"]),
    ("columbus", "Columbus", "Ohio", "US", ["en"]),
    ("edmonton", "Edmonton", "Alberta", "CA", ["en"]),
    ("charlotte", "Charlotte", "North Carolina", "US", ["en"]),
    ("indianapolis", "Indianapolis", "Indiana", "US", ["en"]),
    ("san-francisco", "San Francisco", "California", "US", ["en"]),
    ("seattle", "Seattle", "Washington", "US", ["en"]),
    ("denver", "Denver", "Colorado", "US", ["en"]),
    ("ottawa", "Ottawa", "Ontario", "CA", ["en", "fr"]),
    ("washington", "Washington", "District of Columbia", "US", ["en"]),
    ("boston", "Boston", "Massachusetts", "US", ["en"]),
    ("el-paso", "El Paso", "Texas", "US", ["en", "es"]),
    ("nashville", "Nashville", "Tennessee", "US", ["en"]),
    ("detroit", "Detroit", "Michigan", "US", ["en"]),
    ("winnipeg", "Winnipeg", "Manitoba", "CA", ["en"]),
    ("oklahoma-city", "Oklahoma City", "Oklahoma", "US", ["en"]),
    ("portland", "Portland", "Oregon", "US", ["en"]),
    ("las-vegas", "Las Vegas", "Nevada", "US", ["en"]),
    ("memphis", "Memphis", "Tennessee", "US", ["en"]),
    ("louisville", "Louisville", "Kentucky", "US", ["en"]),
    ("baltimore", "Baltimore", "Maryland", "US", ["en"]),
    ("milwaukee", "Milwaukee", "Wisconsin", "US", ["en"]),
    ("albuquerque", "Albuquerque", "New Mexico", "US", ["en", "es"]),
    ("tucson", "Tucson", "Arizona", "US", ["en", "es"]),
    ("quebec-city", "Quebec City", "Quebec", "CA", ["fr", "en"]),
    ("fresno", "Fresno", "California", "US", ["en", "es"]),
    ("mesa", "Mesa", "Arizona", "US", ["en"]),
    ("sacramento", "Sacramento", "California", "US", ["en"]),
    ("atlanta", "Atlanta", "Georgia", "US", ["en"]),
    ("hamilton", "Hamilton", "Ontario", "CA", ["en"]),
    ("kansas-city", "Kansas City", "Missouri", "US", ["en"]),
    ("colorado-springs", "Colorado Springs", "Colorado", "US", ["en"]),
    ("omaha", "Omaha", "Nebraska", "US", ["en"]),
    ("raleigh", "Raleigh", "North Carolina", "US", ["en"]),
    ("miami", "Miami", "Florida", "US", ["en", "es"]),
    ("long-beach", "Long Beach", "California", "US", ["en"]),
    ("virginia-beach", "Virginia Beach", "Virginia", "US", ["en"]),
    ("oakland", "Oakland", "California", "US", ["en"]),
    ("minneapolis", "Minneapolis", "Minnesota", "US", ["en"]),
    ("tulsa", "Tulsa", "Oklahoma", "US", ["en"]),
    ("kitchener", "Kitchener", "Ontario", "CA", ["en"]),
    ("arlington", "Arlington", "Texas", "US", ["en"]),
    ("new-orleans", "New Orleans", "Louisiana", "US", ["en"]),
    ("wichita", "Wichita", "Kansas", "US", ["en"]),
    ("london-on", "London", "Ontario", "CA", ["en"]),
    ("cleveland", "Cleveland", "Ohio", "US", ["en"]),
    ("tampa", "Tampa", "Florida", "US", ["en"]),
    ("bakersfield", "Bakersfield", "California", "US", ["en", "es"]),
    ("aurora", "Aurora", "Colorado", "US", ["en"]),
    ("anaheim", "Anaheim", "California", "US", ["en", "es"]),
    ("halifax", "Halifax", "Nova Scotia", "CA", ["en"]),
    ("honolulu", "Honolulu", "Hawaii", "US", ["en"]),
    ("santa-ana", "Santa Ana", "California", "US", ["en", "es"]),
    ("riverside", "Riverside", "California", "US", ["en", "es"]),
    ("corpus-christi", "Corpus Christi", "Texas", "US", ["en", "es"]),
    ("lexington", "Lexington", "Kentucky", "US", ["en"]),
    ("victoria", "Victoria", "British Columbia", "CA", ["en"]),
    ("henderson", "Henderson", "Nevada", "US", ["en"]),
    ("stockton", "Stockton", "California", "US", ["en", "es"]),
    ("saint-paul", "Saint Paul", "Minnesota", "US", ["en"]),
    ("cincinnati", "Cincinnati", "Ohio", "US", ["en"]),
    ("st-louis", "St. Louis", "Missouri", "US", ["en"]),
    ("pittsburgh", "Pittsburgh", "Pennsylvania", "US", ["en"]),
    ("greensboro", "Greensboro", "North Carolina", "US", ["en"]),
    ("saskatoon", "Saskatoon", "Saskatchewan", "CA", ["en"]),
    ("lincoln", "Lincoln", "Nebraska", "US", ["en"]),
    ("anchorage", "Anchorage", "Alaska", "US", ["en"]),
    ("plano", "Plano", "Texas", "US", ["en"]),
    ("orlando", "Orlando", "Florida", "US", ["en", "es"]),
    ("irvine", "Irvine", "California", "US", ["en"]),
    ("newark", "Newark", "New Jersey", "US", ["en"]),
    ("regina", "Regina", "Saskatchewan", "CA", ["en"]),
    ("durham", "Durham", "North Carolina", "US", ["en"]),
    ("chula-vista", "Chula Vista", "California", "US", ["en", "es"]),
    ("toledo", "Toledo", "Ohio", "US", ["en"]),
    ("fort-wayne", "Fort Wayne", "Indiana", "US", ["en"]),
    ("st-petersburg", "St. Petersburg", "Florida", "US", ["en"]),
    ("laredo", "Laredo", "Texas", "US", ["en", "es"]),
    ("jersey-city", "Jersey City", "New Jersey", "US", ["en"]),
    ("chandler", "Chandler", "Arizona", "US", ["en"]),
    ("madison", "Madison", "Wisconsin", "US", ["en"]),
    ("buffalo", "Buffalo", "New York", "US", ["en"]),
    ("windsor", "Windsor", "Ontario", "CA", ["en", "fr"]),
    ("burnaby", "Burnaby", "British Columbia", "CA", ["en"]),
]

EUROPE = [
    ("london", "London", "England", "GB", ["en"]),
    ("paris", "Paris", "Ile-de-France", "FR", ["fr", "en"]),
    ("berlin", "Berlin", "Berlin", "DE", ["de", "en"]),
    ("madrid", "Madrid", "Community of Madrid", "ES", ["es", "en"]),
    ("rome", "Rome", "Lazio", "IT", ["it", "en"]),
    ("amsterdam", "Amsterdam", "North Holland", "NL", ["nl", "en"]),
    ("barcelona", "Barcelona", "Catalonia", "ES", ["es", "en"]),
    ("munich", "Munich", "Bavaria", "DE", ["de", "en"]),
    ("milan", "Milan", "Lombardy", "IT", ["it", "en"]),
    ("hamburg", "Hamburg", "Hamburg", "DE", ["de", "en"]),
    ("vienna", "Vienna", "Vienna", "AT", ["de", "en"]),
    ("warsaw", "Warsaw", "Masovia", "PL", ["pl", "en"]),
    ("brussels", "Brussels", "Brussels-Capital", "BE", ["fr", "nl", "en"]),
    ("stockholm", "Stockholm", "Stockholm County", "SE", ["sv", "en"]),
    ("copenhagen", "Copenhagen", "Capital Region", "DK", ["da", "en"]),
    ("dublin", "Dublin", "Leinster", "IE", ["en"]),
    ("lisbon", "Lisbon", "Lisbon District", "PT", ["pt", "en"]),
    ("prague", "Prague", "Prague", "CZ", ["cs", "en"]),
    ("budapest", "Budapest", "Budapest", "HU", ["hu", "en"]),
    ("zurich", "Zurich", "Zurich", "CH", ["de", "en"]),
    ("manchester", "Manchester", "England", "GB", ["en"]),
    ("birmingham", "Birmingham", "England", "GB", ["en"]),
    ("lyon", "Lyon", "Auvergne-Rhone-Alpes", "FR", ["fr", "en"]),
    ("marseille", "Marseille", "Provence-Alpes-Cote d'Azur", "FR", ["fr", "en"]),
    ("frankfurt", "Frankfurt", "Hesse", "DE", ["de", "en"]),
    ("cologne", "Cologne", "North Rhine-Westphalia", "DE", ["de", "en"]),
    ("naples", "Naples", "Campania", "IT", ["it", "en"]),
    ("turin", "Turin", "Piedmont", "IT", ["it", "en"]),
    ("valencia", "Valencia", "Valencian Community", "ES", ["es", "en"]),
    ("seville", "Seville", "Andalusia", "ES", ["es", "en"]),
    ("rotterdam", "Rotterdam", "South Holland", "NL", ["nl", "en"]),
    ("antwerp", "Antwerp", "Flanders", "BE", ["nl", "fr", "en"]),
    ("gothenburg", "Gothenburg", "Vastra Gotaland", "SE", ["sv", "en"]),
    ("oslo", "Oslo", "Oslo", "NO", ["no", "en"]),
    ("helsinki", "Helsinki", "Uusimaa", "FI", ["fi", "en"]),
    ("krakow", "Krakow", "Lesser Poland", "PL", ["pl", "en"]),
    ("bucharest", "Bucharest", "Bucharest", "RO", ["ro", "en"]),
    ("sofia", "Sofia", "Sofia City", "BG", ["bg", "en"]),
    ("athens", "Athens", "Attica", "GR", ["el", "en"]),
    ("geneva", "Geneva", "Geneva", "CH", ["fr", "en"]),
    ("edinburgh", "Edinburgh", "Scotland", "GB", ["en"]),
    ("glasgow", "Glasgow", "Scotland", "GB", ["en"]),
    ("leeds", "Leeds", "England", "GB", ["en"]),
    ("bristol", "Bristol", "England", "GB", ["en"]),
    ("toulouse", "Toulouse", "Occitanie", "FR", ["fr", "en"]),
    ("nice", "Nice", "Provence-Alpes-Cote d'Azur", "FR", ["fr", "en"]),
    ("stuttgart", "Stuttgart", "Baden-Wurttemberg", "DE", ["de", "en"]),
    ("dusseldorf", "Dusseldorf", "North Rhine-Westphalia", "DE", ["de", "en"]),
    ("porto", "Porto", "Porto District", "PT", ["pt", "en"]),
    ("zagreb", "Zagreb", "Zagreb", "HR", ["hr", "en"]),
]

MOYEN_ORIENT = [
    ("dubai", "Dubai", "Dubai", "AE", ["ar", "en"]),
    ("abu-dhabi", "Abu Dhabi", "Abu Dhabi", "AE", ["ar", "en"]),
    ("riyadh", "Riyadh", "Riyadh Province", "SA", ["ar", "en"]),
    ("jeddah", "Jeddah", "Makkah Province", "SA", ["ar", "en"]),
    ("doha", "Doha", "Doha", "QA", ["ar", "en"]),
    ("kuwait-city", "Kuwait City", "Al Asimah", "KW", ["ar", "en"]),
    ("manama", "Manama", "Capital Governorate", "BH", ["ar", "en"]),
    ("muscat", "Muscat", "Muscat Governorate", "OM", ["ar", "en"]),
    ("amman", "Amman", "Amman Governorate", "JO", ["ar", "en"]),
    ("beirut", "Beirut", "Beirut Governorate", "LB", ["ar", "fr", "en"]),
    ("tel-aviv", "Tel Aviv", "Tel Aviv District", "IL", ["he", "en"]),
    ("haifa", "Haifa", "Haifa District", "IL", ["he", "en"]),
    ("istanbul", "Istanbul", "Istanbul Province", "TR", ["tr", "en"]),
    ("ankara", "Ankara", "Ankara Province", "TR", ["tr", "en"]),
    ("izmir", "Izmir", "Izmir Province", "TR", ["tr", "en"]),
    ("cairo", "Cairo", "Cairo Governorate", "EG", ["ar", "en"]),
    ("alexandria", "Alexandria", "Alexandria Governorate", "EG", ["ar", "en"]),
    ("giza", "Giza", "Giza Governorate", "EG", ["ar", "en"]),
    ("sharjah", "Sharjah", "Sharjah", "AE", ["ar", "en"]),
    ("ajman", "Ajman", "Ajman", "AE", ["ar", "en"]),
    ("ras-al-khaimah", "Ras Al Khaimah", "Ras Al Khaimah", "AE", ["ar", "en"]),
    ("al-ain", "Al Ain", "Abu Dhabi", "AE", ["ar", "en"]),
    ("dammam", "Dammam", "Eastern Province", "SA", ["ar", "en"]),
    ("mecca", "Mecca", "Makkah Province", "SA", ["ar", "en"]),
    ("medina", "Medina", "Al Madinah Province", "SA", ["ar", "en"]),
    ("khobar", "Al Khobar", "Eastern Province", "SA", ["ar", "en"]),
    ("dhahran", "Dhahran", "Eastern Province", "SA", ["ar", "en"]),
    ("tabuk", "Tabuk", "Tabuk Province", "SA", ["ar", "en"]),
    ("abha", "Abha", "Asir Province", "SA", ["ar", "en"]),
    ("taif", "Taif", "Makkah Province", "SA", ["ar", "en"]),
    ("buraydah", "Buraydah", "Al-Qassim Province", "SA", ["ar", "en"]),
    ("al-rayyan", "Al Rayyan", "Al Rayyan", "QA", ["ar", "en"]),
    ("al-wakrah", "Al Wakrah", "Al Wakrah", "QA", ["ar", "en"]),
    ("hawalli", "Hawalli", "Hawalli Governorate", "KW", ["ar", "en"]),
    ("salmiya", "Salmiya", "Hawalli Governorate", "KW", ["ar", "en"]),
    ("riffa", "Riffa", "Southern Governorate", "BH", ["ar", "en"]),
    ("salalah", "Salalah", "Dhofar Governorate", "OM", ["ar", "en"]),
    ("sohar", "Sohar", "Al Batinah North", "OM", ["ar", "en"]),
    ("nizwa", "Nizwa", "Ad Dakhiliyah", "OM", ["ar", "en"]),
    ("zarqa", "Zarqa", "Zarqa Governorate", "JO", ["ar", "en"]),
    ("irbid", "Irbid", "Irbid Governorate", "JO", ["ar", "en"]),
    ("aqaba", "Aqaba", "Aqaba Governorate", "JO", ["ar", "en"]),
    ("tripoli-lb", "Tripoli", "North Governorate", "LB", ["ar", "fr", "en"]),
    ("bursa", "Bursa", "Bursa Province", "TR", ["tr", "en"]),
    ("antalya", "Antalya", "Antalya Province", "TR", ["tr", "en"]),
    ("adana", "Adana", "Adana Province", "TR", ["tr", "en"]),
    ("konya", "Konya", "Konya Province", "TR", ["tr", "en"]),
    ("gaziantep", "Gaziantep", "Gaziantep Province", "TR", ["tr", "en"]),
    ("port-said", "Port Said", "Port Said Governorate", "EG", ["ar", "en"]),
    ("suez", "Suez", "Suez Governorate", "EG", ["ar", "en"]),
]

ASIE = [
    ("tokyo", "Tokyo", "Tokyo Metropolis", "JP", ["ja", "en"]),
    ("singapore", "Singapore", "Singapore", "SG", ["en", "zh"]),
    ("hong-kong", "Hong Kong", "Hong Kong", "HK", ["zh", "en"]),
    ("seoul", "Seoul", "Seoul Capital Area", "KR", ["ko", "en"]),
    ("shanghai", "Shanghai", "Shanghai", "CN", ["zh", "en"]),
    ("beijing", "Beijing", "Beijing", "CN", ["zh", "en"]),
    ("mumbai", "Mumbai", "Maharashtra", "IN", ["hi", "en"]),
    ("delhi", "Delhi", "Delhi", "IN", ["hi", "en"]),
    ("bangalore", "Bangalore", "Karnataka", "IN", ["en", "hi"]),
    ("hyderabad", "Hyderabad", "Telangana", "IN", ["en", "hi"]),
    ("chennai", "Chennai", "Tamil Nadu", "IN", ["en", "hi"]),
    ("pune", "Pune", "Maharashtra", "IN", ["en", "hi"]),
    ("kolkata", "Kolkata", "West Bengal", "IN", ["en", "hi"]),
    ("ahmedabad", "Ahmedabad", "Gujarat", "IN", ["en", "hi"]),
    ("bangkok", "Bangkok", "Bangkok", "TH", ["th", "en"]),
    ("jakarta", "Jakarta", "Jakarta", "ID", ["id", "en"]),
    ("kuala-lumpur", "Kuala Lumpur", "Kuala Lumpur", "MY", ["ms", "en"]),
    ("manila", "Manila", "Metro Manila", "PH", ["en", "tl"]),
    ("ho-chi-minh-city", "Ho Chi Minh City", "Ho Chi Minh City", "VN", ["vi", "en"]),
    ("hanoi", "Hanoi", "Hanoi", "VN", ["vi", "en"]),
    ("taipei", "Taipei", "Taipei", "TW", ["zh", "en"]),
    ("osaka", "Osaka", "Osaka Prefecture", "JP", ["ja", "en"]),
    ("yokohama", "Yokohama", "Kanagawa Prefecture", "JP", ["ja", "en"]),
    ("nagoya", "Nagoya", "Aichi Prefecture", "JP", ["ja", "en"]),
    ("fukuoka", "Fukuoka", "Fukuoka Prefecture", "JP", ["ja", "en"]),
    ("busan", "Busan", "Busan", "KR", ["ko", "en"]),
    ("incheon", "Incheon", "Incheon", "KR", ["ko", "en"]),
    ("shenzhen", "Shenzhen", "Guangdong", "CN", ["zh", "en"]),
    ("guangzhou", "Guangzhou", "Guangdong", "CN", ["zh", "en"]),
    ("chengdu", "Chengdu", "Sichuan", "CN", ["zh", "en"]),
    ("hangzhou", "Hangzhou", "Zhejiang", "CN", ["zh", "en"]),
    ("wuhan", "Wuhan", "Hubei", "CN", ["zh", "en"]),
    ("xian", "Xi'an", "Shaanxi", "CN", ["zh", "en"]),
    ("nanjing", "Nanjing", "Jiangsu", "CN", ["zh", "en"]),
    ("tianjin", "Tianjin", "Tianjin", "CN", ["zh", "en"]),
    ("macau", "Macau", "Macau", "MO", ["zh", "pt", "en"]),
    ("surabaya", "Surabaya", "East Java", "ID", ["id", "en"]),
    ("bandung", "Bandung", "West Java", "ID", ["id", "en"]),
    ("penang", "George Town", "Penang", "MY", ["ms", "en"]),
    ("johor-bahru", "Johor Bahru", "Johor", "MY", ["ms", "en"]),
    ("cebu", "Cebu City", "Central Visayas", "PH", ["en", "tl"]),
    ("davao", "Davao City", "Davao Region", "PH", ["en", "tl"]),
    ("chiang-mai", "Chiang Mai", "Chiang Mai Province", "TH", ["th", "en"]),
    ("phuket", "Phuket", "Phuket Province", "TH", ["th", "en"]),
    ("da-nang", "Da Nang", "Da Nang", "VN", ["vi", "en"]),
    ("colombo", "Colombo", "Western Province", "LK", ["si", "en"]),
    ("dhaka", "Dhaka", "Dhaka Division", "BD", ["bn", "en"]),
    ("karachi", "Karachi", "Sindh", "PK", ["ur", "en"]),
    ("lahore", "Lahore", "Punjab", "PK", ["ur", "en"]),
    ("islamabad", "Islamabad", "Islamabad Capital Territory", "PK", ["ur", "en"]),
]

REGIONS = [
    ("amerique-nord", "USA &amp; Canada", AMERIQUE_NORD),
    ("europe", "Europe", EUROPE),
    ("moyen-orient", "Middle East", MOYEN_ORIENT),
    ("asie", "Asia", ASIE),
]

TOUTES = [(*v, cle) for cle, _, liste in REGIONS for v in liste]

PAYS_NOM = {
    "US": "United States", "CA": "Canada", "GB": "United Kingdom",
    "FR": "France", "DE": "Germany", "ES": "Spain", "IT": "Italy",
    "NL": "Netherlands", "BE": "Belgium", "AT": "Austria", "PL": "Poland",
    "SE": "Sweden", "DK": "Denmark", "IE": "Ireland", "PT": "Portugal",
    "CZ": "Czechia", "HU": "Hungary", "CH": "Switzerland", "NO": "Norway",
    "FI": "Finland", "RO": "Romania", "BG": "Bulgaria", "GR": "Greece",
    "HR": "Croatia", "AE": "United Arab Emirates", "SA": "Saudi Arabia",
    "QA": "Qatar", "KW": "Kuwait", "BH": "Bahrain", "OM": "Oman",
    "JO": "Jordan", "LB": "Lebanon", "IL": "Israel", "TR": "Turkiye",
    "EG": "Egypt", "JP": "Japan", "SG": "Singapore", "HK": "Hong Kong",
    "KR": "South Korea", "CN": "China", "IN": "India", "TH": "Thailand",
    "ID": "Indonesia", "MY": "Malaysia", "PH": "Philippines", "VN": "Vietnam",
    "TW": "Taiwan", "MO": "Macau", "LK": "Sri Lanka", "BD": "Bangladesh",
    "PK": "Pakistan",
}

# Controles a la generation : un doublon de slug ecraserait silencieusement
# une page, et un compte different de ce qu'il a demande passerait inapercu.
_slugs = [v[0] for v in TOUTES]
assert len(_slugs) == len(set(_slugs)), \
    "slugs en double : " + str([s for s in _slugs if _slugs.count(s) > 1][:4])
assert len(AMERIQUE_NORD) == 100, f"USA+Canada : {len(AMERIQUE_NORD)} au lieu de 100"
assert len(EUROPE) == 50, f"Europe : {len(EUROPE)} au lieu de 50"
assert len(MOYEN_ORIENT) == 50, f"Moyen-Orient : {len(MOYEN_ORIENT)} au lieu de 50"
assert len(ASIE) == 50, f"Asie : {len(ASIE)} au lieu de 50"
for _v in TOUTES:
    assert _v[3] in PAYS_NOM, f"{_v[1]} : pays {_v[3]} sans nom"
